name: Build packages on build branch

on:
  push:
    branches: [main]
  pull_request:
    # This is just temporary for testing
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # =====================================================
      # Build
      # =====================================================
      - name: Build JS and CSS resources
        run: |
          cd js
          yarn
          yarn build
