name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: ./js
        run: npm ci
      - name: Install Playwright Browsers
        working-directory: ./js
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        working-directory: ./js
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: ./js/playwright-report/
          retention-days: 30
